# Generated by Django 3.0.1 on 2020-06-07 20:03

from django.db import migrations, models
import materialsearch.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('LuctuerNotes', 'LuctuerNotes'), ('Exams', 'Exams'), ('worcksheet', 'worcksheet'), ('book', 'book'), ('syllabus', 'syllabus')], max_length=60)),
                ('year', models.PositiveIntegerField(default=materialsearch.models.current_year)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
