# Generated by Django 3.0.7 on 2020-06-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialsearch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='name',
        ),
        migrations.AddField(
            model_name='material',
            name='link',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('LuctuerNotes', 'LuctuerNotes'), ('Exam form', 'Exam form'), ('Worcksheet', 'Worcksheet'), ('Book', 'Book'), ('Syllabus', 'Syllabus')], default='Exams', max_length=60),
        ),
        migrations.AddField(
            model_name='material',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
