# Generated by Django 3.0.7 on 2020-06-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialsearch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='dumy',
        ),
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(default='defult_material_img.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('LectureNotes', 'LectureNotes'), ('Exam form', 'Exam form'), ('Worksheet', 'Worksheet'), ('Book', 'Book'), ('Syllabus', 'Syllabus')], max_length=60),
        ),
    ]
