# Generated by Django 3.0.7 on 2020-06-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialsearch', '0002_auto_20200607_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='semester',
            field=models.CharField(choices=[('first semester', 'first semester'), ('second semester', 'second semester'), ('sumer semester', 'sumer semester')], default='first semester', max_length=20),
        ),
    ]
