# Generated by Django 3.0.7 on 2020-06-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialsearch', '0002_auto_20200608_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(default='defult_material_img.jpg', upload_to="'cources'"),
        ),
    ]
