# Generated by Django 3.0.7 on 2020-06-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialsearch', '0003_material_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('LuctuerNotes', 'LuctuerNotes'), ('Exam form', 'Exam form'), ('Worcksheet', 'Worcksheet'), ('Book', 'Book'), ('Syllabus', 'Syllabus')], max_length=60),
        ),
        migrations.AlterField(
            model_name='material',
            name='semester',
            field=models.CharField(choices=[('first semester', 'first semester'), ('second semester', 'second semester'), ('summer semester', 'summer semester')], max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
