# Generated by Django 3.0.7 on 2020-06-09 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materialsearch', '0003_auto_20200608_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materialsearch.Specialty'),
        ),
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(default='defult_material_img.jpg', upload_to='cources'),
        ),
    ]
